version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db
      - shared_db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8888:80" # http://localhost:8888 
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - db
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - shared_db_network
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shared_db_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  db:
    driver: bridge
  shared_db_network:
    name: shared_db_network